#!/bin/sh

set -e

ELEMENTARY_KEY="FE70B91C"

case "$1" in
    remove|purge)
	if [ -x /usr/bin/apt-key ]; then
	    apt-key del "$ELEMENTARY_KEY"
	fi
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
